# Deployment and Service Manifest for Harness CV App Example
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-cv-prom-example-deployment
spec:
  selector:
    matchLabels:
      app: harness-cv-prom-example
  replicas: 1 
  template:
    metadata:
      labels:
        app: harness-cv-prom-example
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: harness-cv-prom-example
          image: tyweis/cv-example:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1 
kind: Service 
metadata: 
  name: harness-cv-prom-example-service
spec:
  selector:
    app: harness-cv-prom-example
  ports:
    - protocol: "TCP"
      port: 8082 
      targetPort: 8082 
  type: LoadBalancer 
